version: '2.4'
services:
  master:
    image: saltstack/salt:latest
    environment:
      SALT_MASTER_CONFIG: '{"auto_accept":true,"file_roots":{"base":["/srv/salt"]}}'
    ports:
      - '4505-4506'
    volumes:
      - ./salt:/srv/salt:ro
  minion:
    image: saltstack/salt:latest
    depends_on:
      - master
    environment:
      SALT_MINION_CONFIG: '{"master":"master"}'
